// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZSwR6dSU35_2ztCUqBplQuR1GgsUYUXY',
    appId: '1:318990018705:web:c4e2ca20b04c7cf5b3f730',
    messagingSenderId: '318990018705',
    projectId: 'project-todo-2e53c',
    authDomain: 'project-todo-2e53c.firebaseapp.com',
    storageBucket: 'project-todo-2e53c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfW0JF4q00xTpwcresPnl_endbGTXfZ2s',
    appId: '1:318990018705:android:1e22e8c31a6c8cbdb3f730',
    messagingSenderId: '318990018705',
    projectId: 'project-todo-2e53c',
    storageBucket: 'project-todo-2e53c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzB3FUHfsgaRlf3VgX3IS0jebjJifMbTY',
    appId: '1:318990018705:ios:2b24eba5fa17fa83b3f730',
    messagingSenderId: '318990018705',
    projectId: 'project-todo-2e53c',
    storageBucket: 'project-todo-2e53c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzB3FUHfsgaRlf3VgX3IS0jebjJifMbTY',
    appId: '1:318990018705:ios:2b24eba5fa17fa83b3f730',
    messagingSenderId: '318990018705',
    projectId: 'project-todo-2e53c',
    storageBucket: 'project-todo-2e53c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZSwR6dSU35_2ztCUqBplQuR1GgsUYUXY',
    appId: '1:318990018705:web:68d76f42d5524b65b3f730',
    messagingSenderId: '318990018705',
    projectId: 'project-todo-2e53c',
    authDomain: 'project-todo-2e53c.firebaseapp.com',
    storageBucket: 'project-todo-2e53c.appspot.com',
  );
}
